#!/usr/bin/perl
use 5.010;
use strict;

use MLDBM qw( DB_File JSON );
use JSON::XS qw( encode_json );

tie my %cookie_jar, 'MLDBM', 'cookiejar.db' or die $!;

say JSON::XS->new->pretty->space_after->encode( \%cookie_jar );
